version: "3.3"

services:
  
  app:
    container_name: app
    build:
      context: .
      dockerfile:
        Dockerfile
    ports:
      - "3333:3000"
    networks:
      - link_stars-net

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - link_stars-net 

networks:
  link_stars-net: